# processing parameters
jet_levels: ['ch']
jetR: [0.2, 0.4, 0.6]

debug_level: 0

do_matching: True
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.0
eta_max: 0.9

do_tagging: False
do_reshuffle: True

beyond_jetR: True
part_levels: ['p', 'h', 'ch']

