# Configuration for intermediary TTree processing into final analysis output objects

targets: 
  - E2C_T_jj
  - E2C_Q_jj
  - E2C_P_jj
  - E2C_M_jj
  - E2C_PM_jj
  - E2C_T_jp
  - E2C_Q_jp
  - E2C_P_jp
  - E2C_M_jp
  - E2C_PM_jp
  - E2C_T_pp
  - E2C_Q_pp
  - E2C_P_pp
  - E2C_M_pp
  - E2C_PM_pp
  - E2C_T_mx
  - E2C_Q_mx
  - E2C_P_mx
  - E2C_M_mx
  - E2C_PM_mx
  - jet_pt

jetR: 0.4

bins:
  pT_bins: ['lin', 0, 200, 200]
  # RL_bins: ['log', 1.0e-3, 1, 30]
  RL_bins: ['log', 1.0e-2, 0.4, 20]
  # pT_part_bins: ['lin', 0, 300, 300]
  # eta_bins: ['lin', -1.0, 1.0, 200]
  # phi_bins: ['lin', 0.0, 6.28, 628]
  # Z_bins: ['lin', 0.0, 1.0, 100]

# - [d, dalpha, q1*asin(0.15*0.5*1.1/pT1) - q2*asin(0.15*0.5*1.1/pT2)]
# - [d, dalpha, q1*asin(0.15*0.5*1.1/pT1) - q2*asin(0.15*0.5*1.1/pT2)]

rules:
  cEEC:
    params:
      ptcut:
        - 1.0
      detacut:
        - 0.008
      dphistarcut:
        - 0.003
        - 0.007
        - 0.010
        - 0.013
    dir:
      - [f, pT1 > ptcut && pT2 > ptcut]
      - [d, dphistar, dphi + q2*asin(0.0825/pT2) - q1*asin(0.0825/pT1)] # for pp (negative B)
      # - [d, dphistar, dphi - q2*asin(0.0825/pT2) + q1*asin(0.0825/pT1)] # for pPb (positive B)
      - [f, abs(deta) > detacut || abs(dphistar) > dphistarcut]
    cEEC:
      tree: pairs
      jj:
        dir:
          - [f, id1 == 0 && id2 == 0]
        E2C_T_jj:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_jj: 
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_jj:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_jj:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_jj:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
      jp:
        dir:
          - [f, (id1 == 0 && id2 != 0) || (id1 != 0 && id2 == 0)]
        E2C_T_jp:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_jp: 
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_jp:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_jp:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_jp:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
      pp:
        dir:
          - [f, (id1 > 0 && id2 > 0) || (id1 < 0 && id2 < 0)]
        E2C_T_pp:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_pp: 
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_pp:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_pp:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_pp:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
      mx:
        dir:
          - [f, (id1 > 0 && id2 < 0) || (id1 < 0 && id2 > 0)]
        E2C_T_mx:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_mx: 
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_mx:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_mx:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_mx:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
  jetpt:
    tree: jets
    jet_pt:
      dir:
        - [h, 1, det jet pt;jet pt;cts, pT_bins, pTsub]