# Configuration for intermediary TTree processing into final analysis output objects

targets: 
  - E2C_T_det_jj
  - E2C_T_gen_jj
  - E2C_T_det_jp
  - E2C_T_gen_jp
  - E2C_T_det_pp
  - E2C_T_gen_pp
  - E2C_T_det_mx
  - E2C_T_gen_mx
  - E2C_Q_det_jj
  - E2C_Q_gen_jj
  - E2C_Q_det_jp
  - E2C_Q_gen_jp
  - E2C_Q_det_pp
  - E2C_Q_gen_pp
  - E2C_Q_det_mx
  - E2C_Q_gen_mx
  - E2C_P_det_jj
  - E2C_P_gen_jj
  - E2C_P_det_jp
  - E2C_P_gen_jp
  - E2C_P_det_pp
  - E2C_P_gen_pp
  - E2C_P_det_mx
  - E2C_P_gen_mx
  - E2C_M_det_jj
  - E2C_M_gen_jj
  - E2C_M_det_jp
  - E2C_M_gen_jp
  - E2C_M_det_pp
  - E2C_M_gen_pp
  - E2C_M_det_mx
  - E2C_M_gen_mx
  - E2C_PM_det_jj
  - E2C_PM_gen_jj
  - E2C_PM_det_jp
  - E2C_PM_gen_jp
  - E2C_PM_det_pp
  - E2C_PM_gen_pp
  - E2C_PM_det_mx
  - E2C_PM_gen_mx
  - jet_pt_det
  - jet_pt_gen

jetR: 0.4

bins:
  pT_bins: ['lin', 0, 200, 200]
  # RL_bins: ['log', 1.0e-3, 1, 30]
  RL_bins: ['log', 1.0e-2, 0.4, 20]

rules:
  cEEC:
    params:
      ptcut:
        - 1.0
      detacut:
        - 0.008
      dphistarcut:
        - 0.003
        - 0.007
        - 0.010
        - 0.013
    dir:
      - [f, pT1 > ptcut && pT2 > ptcut]
    cEEC_det:
      tree: pairs_det
      dir:
        - [d, dphistar, dphi + q2*asin(0.0825/pT2) - q1*asin(0.0825/pT1)] # for pp (negative B)
        # - [d, dphistar, dphi - q2*asin(0.0825/pT2) + q1*asin(0.0825/pT1)] # for pPb (positive B)
        - [f, abs(deta) > detacut || abs(dphistar) > dphistarcut]
      jj:
        dir:
          - [f, id1 == 0 && id2 == 0]
        E2C_T_det_jj:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_det_jj:
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_det_jj:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_det_jj:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_det_jj:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
      jp:
        dir:
          - [f, (id1 == 0 && id2 != 0) || (id1 != 0 && id2 == 0)]
        E2C_T_det_jp:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_det_jp:
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_det_jp:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_det_jp:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_det_jp:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
      pp:
        dir:
          - [f, (id1 > 0 && id2 > 0) || (id1 < 0 && id2 < 0)]
        E2C_T_det_pp:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_det_pp:
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_det_pp:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_det_pp:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_det_pp:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
      mx:
        dir:
          - [f, (id1 > 0 && id2 < 0) || (id1 < 0 && id2 > 0)]
        E2C_T_det_mx:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_det_mx:
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_det_mx:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_det_mx:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_det_mx:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
    cEEC_gen:
      tree: pairs_gen
      jj:
        dir:
          - [f, id1 == 0 && id2 == 0]
        E2C_T_gen_jj:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_gen_jj:
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_gen_jj:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_gen_jj:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_gen_jj:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
      jp:
        dir:
          - [f, (id1 == 0 && id2 != 0) || (id1 != 0 && id2 == 0)]
        E2C_T_gen_jp:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_gen_jp:
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_gen_jp:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_gen_jp:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_gen_jp:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
      pp:
        dir:
          - [f, (id1 > 0 && id2 > 0) || (id1 < 0 && id2 < 0)]
        E2C_T_gen_pp:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_gen_pp:
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_gen_pp:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_gen_pp:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_gen_pp:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
      mx:
        dir:
          - [f, (id1 > 0 && id2 < 0) || (id1 < 0 && id2 > 0)]
        E2C_T_gen_mx:
          dir:
            - [h, 2, "eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_Q_gen_mx:
          dir:
            - [d, qw, q1 * q2 * weight]
            - [h, 2, "eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, qw]
        E2C_P_gen_mx:
          dir:
            - [f, q1 > 0 && q2 > 0]
            - [h, 2, "eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_M_gen_mx:
          dir:
            - [f, q1 < 0 && q2 < 0]
            - [h, 2, "eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
        E2C_PM_gen_mx:
          dir:
            - [f, (q1 * q2) < 0]
            - [h, 2, "eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjetsub, RL, weight]
  jetpt:
    det:
      tree: jets_det
      jet_pt_det:
        dir:
          - [h, 1, det jet pt;jet pt;cts, pT_bins, pTsub]
    gen:
      tree: jets_gen
      jet_pt_gen:
        dir:
          - [h, 1, gen jet pt;jet pt;cts, pT_bins, pTsub]