# Configuration for:
#   (a) Processing of ROOT trees into histograms
#   (b) Analysis of histograms into final result
#
# The observables are structured into observable blocks (e.g. theta_g, subjet_z, etc.)
# each containing multiple individual subconfigurations (e.g. zcut, beta, subjetR, etc.),
# where each subconfiguration corresponds to a single unfolded result.
# One can also specify a list of jetR, which will be looped over.
#
# The process step is intended to loop over all observables simultaneously
# The analysis step is intended to run for a single observable block

process_observables: ['unfold']
jetR: [0.4] #, 0.7]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
mc_fraction_threshold: 0.5
reject_tracks_fraction: 0.0
eta_max: 0.9
debug_level: 0
dry_run: False
fast_simulation: False
ENC_fastsim: False # only set to True when fast_simulation is set to True
ENC_pair_cut: False

mult_threshold: [] #122
do_median_subtraction: True
do_perpendicular_cone: True
mixed_cone: True
apply_track_pT_cut: True
# weight_binning: [1.0e-5, 1, 20]
weight_binning: [3.0e-5, 1, 8]
# RL_binning: [0.005, 1, 22]
RL_binning: [0.008, 1, 10]
# RL_binning: [1.0e-3, 1, 30]
pT_truth_bins: [5.0, 10.0, 20., 40., 60., 80., 100., 150.]
pT_det_bins: [10.0, 20., 40., 60., 80., 100., 150.]

jetpt_min_truth: 5.0
jetpt_min_det: 5.0
jetpt_min_det_subtracted: 5.0

# Observable block
unfold:
  config1:
    thrd: 1.0