# Configuration for intermediary TTree processing into final analysis output objects

targets: 
  # - E2C_T_det
  # - E2C_Q_det
  # - E2C_P_det
  # - E2C_M_det
  # - E2C_PM_det
  # - E2C_T_gen
  # - E2C_Q_gen
  # - E2C_P_gen
  # - E2C_M_gen
  # - E2C_PM_gen
  # - jet_pt_det
  # - jet_pt_det_detvsgen
  # - jet_pt_gen
  # - jet_pt_gen_detvsgen
  # - jet_pt_matched_det
  # - jet_pt_matched_gen
  - part_P_gen_pt
  - part_P_reco_gen_pt
  - part_M_gen_pt
  - part_M_reco_gen_pt
  - rsn_P
  - rsn_M


jetR: 0.4

bins:
  # pT_bins: ['lin', 0, 200, 200]
  # RL_bins: ['log', 1.0e-3, 1, 30]
  rsn_part_bins: ['lin', -0.1, 0.1, 100]
  pT_part_bins: ['log', 0.15, 10, 250]

rules:
  cEEC:
    params:
      ptcut:
        - 0.15
        - 0.5
        - 1.0
        - 2.0
    dir:
      - [f, pT1 > ptcut && pT2 > ptcut]
    cEEC_det:
      tree: pairs_det
      E2C_T_det: 
        dir:
          - [h, 2, "det eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, weight]
      E2C_Q_det: 
        dir:
          - [d, qw, q1 * q2 * weight]
          - [h, 2, "det eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, qw]
      E2C_P_det:
        dir:
          - [f, q1 > 0 && q2 > 0]
          - [h, 2, "det eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, weight]
      E2C_M_det:
        dir:
          - [f, q1 < 0 && q2 < 0]
          - [h, 2, "det eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, weight]
      E2C_PM_det:
        dir:
          - [f, (q1 * q2) < 0]
          - [h, 2, "det eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, weight]
    cEEC_gen:
      tree: pairs_gen
      E2C_T_gen: 
        dir:
          - [h, 2, "gen eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, weight]
      E2C_Q_gen: 
        dir:
          - [d, qw, q1 * q2 * weight]
          - [h, 2, "gen eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, qw]
      E2C_P_gen:
        dir:
          - [f, q1 > 0 && q2 > 0]
          - [h, 2, "gen eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, weight]
      E2C_M_gen:
        dir:
          - [f, q1 < 0 && q2 < 0]
          - [h, 2, "gen eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, weight]
      E2C_PM_gen:
        dir:
          - [f, (q1 * q2) < 0]
          - [h, 2, "gen eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, weight]
  jetpt:
    det:
      tree: jets_det
      jet_pt_det:
        dir:
          - [h, 1, det jet pt;jet pt;cts, pT_bins, pT]
    gen:
      tree: jets_gen
      jet_pt_gen:
        dir:
          - [h, 1, gen jet pt;jet pt;cts, pT_bins, pT]
    det_matched:
      tree: jets_det_matched
      jet_pt_matched_det:
        dir:
          - [h, 1, det jet pt;jet pt;cts, pT_bins, pT]
      jet_pt_det_detvsgen:
        dir:
          - [f, match_pT > 0]
          - [h, 2, "det vs gen (det);det pt;gen pt", pT_bins, pT_bins, pT, match_pT]
    gen_matched:
      tree: jets_gen_matched
      jet_pt_matched_gen:
        dir:
          - [h, 1, gen jet pt;jet pt;cts, pT_bins, pT]
      jet_pt_gen_detvsgen:
        dir:
          - [f, match_pT > 0]
          - [h, 2, "det vs gen (gen);det pt;gen pt", pT_bins, pT_bins, match_pT, pT]
  part:
    tree: parts_gen
    part_P:
      dir:
        - [f, q > 0]
      part_P_gen_pt:
        dir:
          - [h, 1, part pt gen P;pt;cts, pT_part_bins, pT]
      part_P_reco_gen_pt:
        dir:
          - [f, match_pT > 0]
          - [h, 1, part pt gen reco P;pt;cts, pT_part_bins, pT]
      rsn_P:
        dir:
          - [f, match_pT > 0]
          - [d, rsn, (match_pT - pT) / pT]
          - [h, 2, "pt rsn;gen pt;rsn [(det-gen) / gen]", pT_part_bins, rsn_part_bins, pT, rsn]
    part_M:
      dir:
        - [f, q < 0]
      part_M_gen_pt:
        dir:
          - [h, 1, part pt gen M;pt;cts, pT_part_bins, pT]
      part_M_reco_gen_pt:
        dir:
          - [f, match_pT > 0]
          - [h, 1, part pt gen reco M;pt;cts, pT_part_bins, pT]
      rsn_M:
        dir:
          - [f, match_pT > 0]
          - [d, rsn, (match_pT - pT) / pT]
          - [h, 2, "pt rsn;gen pt;rsn [(det-gen) / gen]", pT_part_bins, rsn_part_bins, pT, rsn]
