# Configuration for intermediary TTree processing into final analysis output objects

targets: 
  - uwE2C_T_det
  - uwE2C_Q_det
  - uwE2C_P_det
  - uwE2C_M_det
  - uwE2C_PM_det
  - uwE2C_T_gen
  - uwE2C_Q_gen
  - uwE2C_P_gen
  - uwE2C_M_gen
  - uwE2C_PM_gen
  - jet_pt_det
  # - jet_pt_det_detvsgen
  - jet_pt_gen
  # - jet_pt_gen_detvsgen
  # - jet_pt_matched_det
  # - jet_pt_matched_gen
  # - part_gen_pt
  # - part_reco_gen_pt
  # - rsn


jetR: 0.4

bins:
  pT_bins: ['lin', 0, 200, 200]
  RL_bins: ['log', 1.0e-3, 1, 30]

rules:
  cEEC:
    params:
      ptcut:
        - 1.0
    dir:
      - [f, pT1 > ptcut && pT2 > ptcut]
    cEEC_det:
      tree: pairs_det
      uwE2C_T_det: 
        dir:
          - [h, 2, "det eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL]
      uwE2C_Q_det: 
        dir:
          - [d, qprod, q1 * q2]
          - [h, 2, "det eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, qprod]
      uwE2C_P_det:
        dir:
          - [f, q1 > 0 && q2 > 0]
          - [h, 2, "det eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL]
      uwE2C_M_det:
        dir:
          - [f, q1 < 0 && q2 < 0]
          - [h, 2, "det eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL]
      uwE2C_PM_det:
        dir:
          - [f, (q1 * q2) < 0]
          - [h, 2, "det eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL]
    cEEC_gen:
      tree: pairs_gen
      uwE2C_T_gen: 
        dir:
          - [h, 2, "gen eec T;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL]
      uwE2C_Q_gen: 
        dir:
          - [d, qprod, q1 * q2]
          - [h, 2, "gen eec Q;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL, qprod]
      uwE2C_P_gen:
        dir:
          - [f, q1 > 0 && q2 > 0]
          - [h, 2, "gen eec P;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL]
      uwE2C_M_gen:
        dir:
          - [f, q1 < 0 && q2 < 0]
          - [h, 2, "gen eec M;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL]
      uwE2C_PM_gen:
        dir:
          - [f, (q1 * q2) < 0]
          - [h, 2, "gen eec PM;jet pt;R_{L}", pT_bins, RL_bins, pTjet, RL]
  jetpt:
    det:
      tree: jets_det
      jet_pt_det:
        dir:
          - [h, 1, det jet pt;jet pt;cts, pT_bins, pT]
    gen:
      tree: jets_gen
      jet_pt_gen:
        dir:
          - [h, 1, gen jet pt;jet pt;cts, pT_bins, pT]