jetR: 0.4

reject_tail: 2.5

RL_binning: [1.0E-2, 0.4, 20] # the period is important as otherwise PyYAML will read it as a string
pT_binning: [0, 200, 200]
scale_binning: [0, 100000, 2000]
pdf_binning: [0, 1000, 2000]
ratio_binning: [1.0E-2, 20, 400]